### ISSUE TITLE
Images in Mobile App and Steps to get started

### ISSUE THREAD

**Issue by anushav9** [anushav9/lm-anusha#4]
Size of the images in these sections need to be adjusted.

**Comment by mikecreuzer** [comment]
to what? Do it, you should/need to know how to simply resize images.

Make sure you always resize source, NOT exported versions, since those will have already been optimized for web (kraken.io, tinypng, photoshop export tool, etc) - Resizing an already optimized photo is not ideal since it will force you to optimize and already optimized image, thus loosing quality of the image unnecessarily.
